#!/bin/bash
nfs_status=`lsmod | grep nfsd`
if [ -z "$nfs_status" ]; then
  sudo modprobe nfsd
  nfs_status=`lsmod | grep nfsd`
  if [ -z "$nfs_status" ]; then
    sudo apt update;sudo apt install -y nfs-kernel-server
  fi
else
    echo "NFS server is running successfully"
fi
